name: Data Updater

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  update-data:
    name: Updating data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6' ]
    steps:
      - uses: actions/checkout@master
      - name: Preparing adapter repo
        uses: actions/checkout@master
        with:
          repository: ammitto/adapters
          path: adapters
      - name: Show directory structure 1
        shell: bash
        run: |
          pwd
          ls
      - name: Show directory structure 2
        shell: bash
        run: |
          cd adapters && ls
      - name: Show directory structure 3
        shell: bash
        run: |
          pwd
          ls