name: Data Updater

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  update-data:
    name: Updating data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6' ]
    steps:
      - name: Show Update Log
        shell: bash
        run: |
          echo $GITHUB_WORKSPACE



